os:
  - linux
language: ruby
sudo: required
dist: trusty

addons:
  artifacts:
    debug: true
    paths:
      - ./reports/html-report
      - ./reports/xml-report
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: simplelance
    s3_region: us-west-1
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  packages:
    - unzip
    - libappindicator1 
    - fonts-liberation
    - xvfb
before_install:
  - docker pull loyaltyone/docker-alpine-java-node
  - wget `curl -s https://api.github.com/repos/getgauge-examples/activeadmin-demo/releases/latest | grep browser_download_url | cut -d '"' -f 4`
  - docker run -d -v=`pwd`:$HOME/host -p 127.0.0.1:8080:8080 loyaltyone/docker-alpine-java-node java -jar $HOME/host/activeadmin-demo.war
  - docker ps -a
install:
  - sh ./install_latest_gauge.sh /tmp
  - source ~/.profile
  - gauge install ruby
  - bundle install
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - chmod +x ~/Downloads/chromedriver
  - sudo mv -f ~/Downloads/chromedriver /usr/bin/chromedriver
  - Xvfb :0 -ac -screen 0 1024x768x24 &

script:
  - headless=Y bundle exec gauge specs
