os:
  - linux
language: ruby
sudo: required
dist: trusty

addons:
  artifacts:
    debug: true
    paths:
      - ./reports/html-report
      - ./reports/xml-report
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: simplelance
    s3_region: us-west-1
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  packages:
    - unzip
    - libappindicator1 
    - fonts-liberation
    - xvfb
install:
  - sh ./install_latest_gauge.sh /tmp
  - source ~/.profile
  - gauge install ruby
  - bundle install
  - wget -P $HOME `curl -s https://api.github.com/repos/getgauge-examples/activeadmin-demo/releases/latest | grep browser_download_url | cut -d '"' -f 4`
  - java -jar $HOME/activeadmin-demo.war &
  - sleep 30
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - chmod +x ~/Downloads/chromedriver
  - sudo mv -f ~/Downloads/chromedriver /usr/bin/chromedriver
  - Xvfb :0 -ac -screen 0 1024x768x24 &

script:
  - headless=Y bundle exec gauge specs
